### ISSUE TITLE
[FR]: having MultiClass for PCs

### ISSUE THREAD

**Issue by namtrah** [javalent/initiative-tracker#130]
I have begun to have PCs with Multi-classes and it is not possible in IT to use them. I have to fake it by adding the two levels into one like this:
```yaml
level: 4
```
I'd like to request a new field for PCs named `multiclass` which has the following fields:
```yaml
multiclass:
  - name: Cleric
    - subclass: Light Domain
    - level: 3
  - name: Monk
    - subclass: Drunken Master
    - level: 2
```
Which would allow me to have the metadata necessary for other things as well as two levels that could be added together for a total IT level of 5. This would have to override the variable `level` most definitely, but can bring out new possibilities to using PCs in IT.
